### ISSUE TITLE
Blocks won't finalize

### ISSUE THREAD

**Issue by gregdhill** [kurtosis-tech/ethereum-package#376]
Started a local devnet using the default network parameters but it will not finalize any blocks (even after multiple epochs).

```shell
$ kurtosis version
CLI Version:   0.85.38

kurtosis run --enclave my-testnet github.com/kurtosis-tech/ethereum-package
...
```

Additionally, when I build the network with the following parameters there are supposedly no active validators (according to Dora):

```yaml
participants:
  - el_client_type: geth
    cl_client_type: prysm
    count: 3
```
