### ISSUE TITLE
Nimbus CL not starting

### ISSUE THREAD

**Issue by bsamuels453** [kurtosis-tech/ethereum-package#417]
logs:
```
NOT 2023-12-14 17:36:08.358+00:00 Starting metrics HTTP server               topics="beacnde" url=http://0.0.0.0:8008/metrics
WRN 2023-12-14 17:36:08.358+00:00 Unknown constants in config file           unknowns="@[\"MAXIMUM_GOSSIP_CLOCK_DISPARITY\", \"MAX_REQUEST_BLOB_SIDECARS\", \"MAX_BLOBS_PER_BLOCK\", \"MIN_EPOCHS_FOR_BLOCK_REQUESTS\", \"MESSAGE_DOMAIN_VALID_SNAPPY\"]"
INF 2023-12-14 17:36:08.359+00:00 Threadpool started                         topics="beacnde" numThreads=4
NOT 2023-12-14 17:36:08.469+00:00 Database initialized from genesis          blockRoot=2896447da3e4cd778ef2b252e7026577acfff048a540a39e9b49369af6680e8e stateRoot=bdf166d2b9cf8ca1a023d08640e6c7e98c2fa897b46795fe3b1f045b62e6cd6a stateSlot=0
INF 2023-12-14 17:36:08.469+00:00 Loading block DAG from database            topics="beacnde" path=$HOME/consensus-data/db
INF 2023-12-14 17:36:08.698+00:00 Loading finalized blocks                   finHigh=none() finalizedHead=2896447d:0
INF 2023-12-14 17:36:08.698+00:00 Block DAG initialized                      head=2896447d:0 finalizedHead=2896447d:0 tail=2896447d:0 backfill="(0, \"00000000\")" loadDur=7ms609us150ns summariesDur=98ms221us546ns finalizedDur=123ms380us543ns frontfillDur=49ns keysDur=59us796ns
NOT 2023-12-14 17:36:08.745+00:00 Starting REST HTTP server                  topics="beacnde" url=http://0.0.0.0:4000/
INF 2023-12-14 17:36:08.745+00:00 Generating new networking key              topics="networking" network_public_key=0802122103d862f471748e198823fefeaa1b6d417a1d947e9713787d743ba1fc688a6b4db9 network_peer_id=16Uiu2HAmTDfvsAM1joM8rDBo5oHPi926LhWKtCajYXbEZJCg91T6
INF 2023-12-14 17:36:08.746+00:00 Adding privileged direct peer              topics="beacnde" peerId=16U*pMJ7uV address=/ip4/10.245.34.232/tcp/9000
INF 2023-12-14 17:36:08.746+00:00 Adding privileged direct peer              topics="beacnde" peerId=16U*pZY9ar address=/ip4/10.245.132.73/udp/12000
INF 2023-12-14 17:36:08.746+00:00 Adding privileged direct peer              topics="beacnde" peerId=16U*keY3aB address=/ip4/10.245.121.221/udp/12000
INF 2023-12-14 17:36:08.746+00:00 Adding privileged direct peer              topics="beacnde" peerId=16U*fiVBbN address=/ip4/10.245.104.183/tcp/9000
INF 2023-12-14 17:36:08.746+00:00 Adding privileged direct peer              topics="beacnde" peerId=16U*yS25vE address=/ip4/10.245.135.163/tcp/9000
INF 2023-12-14 17:36:08.747+00:00 Discovery ENR initialized                  topics="eth p2p discv5" enrAutoUpdate=false seqNum=1 ip=some(10.245.120.130) tcpPort=some(9000) udpPort=some(9000) customEnrFields="@[eth2:0xA66B6276400000380100000000000000, attnets:0x0000000000000000]" uri=enr:-LK4QMQKSBPuTpjhkNAmht_xYgearVzpN67ddsUxuNZji3DdYmSiDkALi-598hLmRs0c7cut42hQNPX3YmW4IDId-uQBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpCma2J2QAAAOAEAAAAAAAAAgmlkgnY0gmlwhAr1eIKJc2VjcDI1NmsxoQPYYvRxdI4ZiCP-_qobbUF6HZR-lxN4fXQ7ofxoimtNuYN0Y3CCIyiDdWRwgiMo
INF 2023-12-14 17:36:08.747+00:00 Loading slashing protection database (v2)  topics="beacnde" path=/validator-keys/node-5-keystores/nimbus-keys
FAT 2023-12-14 17:36:08.747+00:00 Failed to open slashing protection database topics="beacnde" databasePath=/validator-keys/node-5-keystores/nimbus-keys databaseName=slashing_protection
```

network config:
```
participants:
  - el_client_type: geth
    el_client_image: ethereum/client-go:latest
    cl_client_type: lighthouse
    cl_client_image: sigp/lighthouse:latest
    el_min_cpu: 1000
    el_max_cpu: 1000
    el_min_mem: 1024
    el_max_mem: 1024
    bn_min_cpu: 2000
    bn_max_cpu: 3000
    bn_min_mem: 2048
    bn_max_mem: 2048
    v_min_cpu: 1000
    v_max_cpu: 1000
    v_min_mem: 1028
    v_max_mem: 1028
    count: 1
  - el_client_type: geth
    el_client_image: ethereum/client-go:latest
    cl_client_type: prysm
    cl_client_image: prysmaticlabs/prysm-beacon-chain:latest,prysmaticlabs/prysm-validator:latest
    el_min_cpu: 1000
    el_max_cpu: 1000
    el_min_mem: 1024
    el_max_mem: 1024
    bn_min_cpu: 2000
    bn_max_cpu: 3000
    bn_min_mem: 3072
    bn_max_mem: 3072
    v_min_cpu: 1000
    v_max_cpu: 1000
    v_min_mem: 1028
    v_max_mem: 1028
    count: 1
  - el_client_type: geth
    el_client_image: ethereum/client-go:latest
    cl_client_type: prysm
    cl_client_image: prysmaticlabs/prysm-beacon-chain:latest,prysmaticlabs/prysm-validator:latest
    el_min_cpu: 1000
    el_max_cpu: 1000
    el_min_mem: 1024
    el_max_mem: 1024
    bn_min_cpu: 2000
    bn_max_cpu: 3000
    bn_min_mem: 3072
    bn_max_mem: 3072
    v_min_cpu: 1000
    v_max_cpu: 1000
    v_min_mem: 1028
    v_max_mem: 1028
    count: 1
  - el_client_type: reth
    el_client_image: ghcr.io/paradigmxyz/reth:v0.1.0-alpha.13
    cl_client_type: lighthouse
    cl_client_image: sigp/lighthouse:latest
    el_min_cpu: 1000
    el_max_cpu: 1000
    el_min_mem: 1024
    el_max_mem: 1024
    bn_min_cpu: 2000
    bn_max_cpu: 3000
    bn_min_mem: 2048
    bn_max_mem: 2048
    v_min_cpu: 1000
    v_max_cpu: 1000
    v_min_mem: 1028
    v_max_mem: 1028
    count: 1
  - el_client_type: reth
    el_client_image: ghcr.io/paradigmxyz/reth:v0.1.0-alpha.13
    cl_client_type: teku
    cl_client_image: consensys/teku:23.12.0
    el_min_cpu: 1000
    el_max_cpu: 1000
    el_min_mem: 1024
    el_max_mem: 1024
    bn_min_cpu: 2000
    bn_max_cpu: 3000
    bn_min_mem: 2048
    bn_max_mem: 2048
    v_min_cpu: 1000
    v_max_cpu: 1000
    v_min_mem: 1028
    v_max_mem: 1028
    count: 1
  - el_client_type: reth
    el_client_image: ghcr.io/paradigmxyz/reth:v0.1.0-alpha.13
    cl_client_type: nimbus
    cl_client_image: statusim/nimbus-eth2:amd64-v23.10.0
    el_min_cpu: 1000
    el_max_cpu: 1000
    el_min_mem: 1024
    el_max_mem: 1024
    bn_min_cpu: 2000
    bn_max_cpu: 3000
    bn_min_mem: 2048
    bn_max_mem: 2048
    v_min_cpu: 1000
    v_max_cpu: 1000
    v_min_mem: 1028
    v_max_mem: 1028
    count: 1
  - el_client_type: reth
    el_client_image: ghcr.io/paradigmxyz/reth:v0.1.0-alpha.13
    cl_client_type: lodestar
    cl_client_image: chainsafe/lodestar:v1.12.1
    el_min_cpu: 1000
    el_max_cpu: 1000
    el_min_mem: 1024
    el_max_mem: 1024
    bn_min_cpu: 2000
    bn_max_cpu: 3000
    bn_min_mem: 2048
    bn_max_mem: 2048
    v_min_cpu: 1000
    v_max_cpu: 1000
    v_min_mem: 1028
    v_max_mem: 1028
    count: 1

network_params:
  # This needs to be set to ensure that path based storage is disabled on geth (older version doesn't yet support it)
  capella_fork_epoch: 1
  num_validator_keys_per_node: 32
additional_services:
  - prometheus_grafana
parallel_keystore_generation: true

```
