### ISSUE TITLE
Besu star issue

### ISSUE THREAD

**Issue by nick-staked** [kurtosis-tech/ethereum-package#444]
https://github.com/kurtosis-tech/ethereum-package/blob/main/src/el/besu/besu_launcher.star#L257

```
There was an error interpreting Starlark code 
Evaluation error: Multiple errors caught interpreting the Starlark script. Listing each of them below.
	at [github.com/kurtosis-tech/ethereum-package/src/el/besu/besu_launcher.star:257:14]: undefined: User
	at [github.com/kurtosis-tech/ethereum-package/src/participant_network.star:16:21]: <toplevel>
	at [github.com/kurtosis-tech/ethereum-package/main.star:3:36]: <toplevel>

Error encountered running Starlark code.
```

**Comment by barnabasbusa** [comment]
Please make sure you update your kurtosis version.

**Comment by nick-staked** [comment]
What version should I be running?
```
A Kurtosis engine is running with the following info:
Version:   0.86.1
```

**Comment by barnabasbusa** [comment]
0.86.1 should be working. 

Can you confirm that your CLI is also on 86.1?

**Comment by nick-staked** [comment]
```
CLI Version:   0.86.1

To see the engine version (provided it is running): kurtosis engine status
```

**Comment by barnabasbusa** [comment]
can you please paste your yaml config?

**Comment by h4ck3rk3y** [comment]
@nick-staked run `kurtosis engine status`; or restart engine!

**Comment by nick-staked** [comment]
```
> kurtosis engine status
A Kurtosis engine is running with the following info:
Version:   0.86.1
```

**Comment by nick-staked** [comment]
This is after a restart ^

**Comment by nick-staked** [comment]
It appears the issue is within my config. The default is working now

**Comment by h4ck3rk3y** [comment]
can you share the configuration?

i am wondering if you are running against an old enclave

**Comment by nick-staked** [comment]
Apologies for the delay.
```yaml
participants:
  - el_client_type: geth
    el_client_image: ethereum/client-go:latest
    el_client_log_level: ""
    el_extra_params: []
    el_extra_labels: {}
    cl_client_type: lighthouse
    cl_client_image: sigp/lighthouse:latest
    count: 2
    prometheus_config:
      scrape_interval: 15s
      labels: {}
    blobber_enabled: false
    blobber_extra_params: []
  - el_client_type: besu
    el_client_image: hyperledger/besu
    cl_client_type: teku
    cl_client_image: consensys/teku
    count: 2
  - el_client_type: reth
    el_client_image: ghcr.io/paradigmxyz/reth:latest
    cl_client_type: lighthouse
    cl_client_image: sigp/lighthouse:latest
    count: 2
  - el_client_type: geth
    el_client_image: ethereum/client-go:latest
    cl_client_type: prysm
    cl_client_image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest,gcr.io/prysmaticlabs/prysm/validator:latest
    count: 2
network_params:
  network_id: "3151908"
  deposit_contract_address: "0x4242424242424242424242424242424242424242"
  seconds_per_slot: 12
  num_validator_keys_per_node: 64
  preregistered_validator_keys_mnemonic:
    "giant issue aisle success illegal bike spike
    question tent bar rely arctic volcano long crawl hungry vocal artwork sniff fantasy
    very lucky have athlete"
  preregistered_validator_count: 0
  genesis_delay: 120
  max_churn: 8
  ejection_balance: 16000000000
  capella_fork_epoch: 0
  deneb_fork_epoch: 4
  electra_fork_epoch: null
additional_services:
  - tx_spammer
  - blob_spammer
  - el_forkmon
  - beacon_metrics_gazer
  - dora
  - prometheus_grafana
wait_for_finalization: false
global_client_log_level: info
snooper_enabled: false
ethereum_metrics_exporter_enabled: false
parallel_keystore_generation: false
mev_type: null
mev_params:
  mev_relay_image: flashbots/mev-boost-relay
  mev_relay_api_extra_args: []
  mev_relay_housekeeper_extra_args: []
  mev_relay_website_extra_args: []
  mev_builder_extra_args: []
  mev_builder_prometheus_config:
    scrape_interval: 15s
    labels: {}
  mev_flood_image: flashbots/mev-flood
  mev_flood_extra_args: []
  mev_flood_seconds_per_bundle: 15
grafana_additional_dashboards: []
persistent: False
```
This was working last week but broke this morning.

**Comment by nick-staked** [comment]
@h4ck3rk3y I ran `kurtosis enclave rm -f my-testnet` is there a better way to clear the old enclave?

**Comment by barnabasbusa** [comment]
you can run `kurtosis clean -a` that will wipe all your enclaves.

**Comment by nick-staked** [comment]
@barnabasbusa thank you, that seems to have fixed my issue :thinking:. The config is working unchanged now

**Comment by barnabasbusa** [comment]
Great. By the way, you don't need to use the default keys.

So your config can be rewritten to a much shorter yaml file:

```yaml
participants:
  - el_client_type: geth
    cl_client_type: lighthouse
    count: 2
  - el_client_type: besu
    cl_client_type: teku
    count: 2
  - el_client_type: reth
    cl_client_type: lighthouse
    count: 2
  - el_client_type: geth
    cl_client_type: prysm
    count: 2
```
