### ISSUE TITLE
add `reconstruct-historic-states` cl cmd and `MIN_VALIDATOR_WITHDRAWABILITY_DELAY` config

### ISSUE THREAD

**Issue by icesfeathers** [kurtosis-tech/ethereum-package#476]
- Add the `--reconstruct-historic-states` command to start cl to facilitate querying old epoch info;
- Adding configuration information such as `MIN_VALIDATOR_WITHDRAWABILITY_DELAY` and `MAX_SEED_LOOKAHEAD` can extend the validator exit time > the synchronization committee time and avoid continuing to generate income in the `withdrawal_done` state.

If the second point is adopted, please tell me the latest modified branch

**Comment by barnabasbusa** [comment]
1. you can add extra cl flags to your start up argument by adding it to `participant.beacon_extra_params array`.

E.g
```yaml
participants:
  - el_client_type: geth
    el_client_image: ethpandaops/geth:verkle-costs-activation-switch-0f04aba
    cl_client_type: lighthouse
    cl_client_image: ethpandaops/lighthouse:verkle-trees-capella-2ffb8a9
    beacon_extra_params array:
       - "--reconstruct-historic-states"
  - el_client_type: geth
    el_client_image: ethpandaops/geth:verkle-costs-activation-switch-0f04aba
    cl_client_type: lodestar
    cl_client_image: ethpandaops/lodestar:g11tech-verge-815364b
network_params:
  electra_fork_epoch: 1
  network: holesky-shadowfork-verkle
additional_services:
  - dora
 ```
 
 2. Once https://github.com/ethpandaops/ethereum-genesis-generator/pull/94 merged, I'll open a new PR where MIN_VALIDATOR_WITHDRAWABILITY_DELAY can be configured. `MAX_SEED_LOOKAHEAD` is a preset, and can't be adjusted by the config parameters.
