### ISSUE TITLE
Run single Lodestar beacon node

### ISSUE THREAD

**Issue by nflaig** [kurtosis-tech/ethereum-package#555]
Right now it's not possible to run just a single Lodestar beacon node without passing additional params

This configuration works
```yaml
participants:
  - el_type: geth
    el_image: ethereum/client-go:stable
    cl_type: lodestar
    cl_image: chainsafe/lodestar:next
    cl_extra_params:
      - --sync.isSingleNode
      - --network.allowPublishToZeroPeers
    vc_type: teku
    vc_image: consensys/teku:latest
    count: 1
```

But would it be possible to detect if there is just one node (participant) and automatically set the `cl_extra_params` as in the provided config?
