### ISSUE TITLE
"String has no .name field or method" when using unsupported CL client

### ISSUE THREAD

**Issue by MegaRedHand** [kurtosis-tech/ethereum-package#576]
Running `kurtosis run github.com/kurtosis-tech/ethereum-package --args-file network_params.yaml` with `networks_params.yaml` being:
```yaml
participants:
  - el_type: geth
    cl_type: foo
    cl_image: bar
    vc_type: lighthouse
    validator_count: null
    count: 2
```

Results in the error:
```
Evaluation error: string has no .name field or method
        at [github.com/kurtosis-tech/ethereum-package/main.star:104:55]: run
        at [github.com/kurtosis-tech/ethereum-package/src/participant_network.star:166:34]: launch_participant_network
        at [github.com/kurtosis-tech/ethereum-package/src/cl/cl_launcher.star:117:42]: launch
```
