### ISSUE TITLE
max epoch churn limit not set for pre deneb genesis

### ISSUE THREAD

**Issue by nflaig** [kurtosis-tech/ethereum-package#650]
Setting deneb fork epoch > 1 generates an invalid config
```yaml
network_params:
  deneb_fork_epoch: 1
```
The config does not set any value for max epoch churn limit

> files/el_cl_genesis_data/config.yaml
```
# [New in Deneb:EIP7514] 2**3 (= 8)
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 
```

This causes issue for Lodestar at startup
```
 == SERVICE 'cl-1-lodestar-geth' LOGS ===================================
   ✖ Error: Invalid MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT value null expected string
```

This seems to be a rather new issue as I was running pre deneb genesis networks before without any issues.

Complete config used
```yaml
participants:
  - el_type: geth
    el_image: ethereum/client-go:stable
    cl_type: lodestar
    cl_image: chainsafe/lodestar:latest
    vc_type: lighthouse
    vc_image: sigp/lighthouse:latest
    count: 1
  - el_type: geth
    el_image: ethereum/client-go:stable
    cl_type: lighthouse
    cl_image: sigp/lighthouse:latest
    vc_type: lodestar
    vc_image: chainsafe/lodestar:latest
    count: 1
network_params:
  deneb_fork_epoch: 1
  genesis_delay: 60
  num_validator_keys_per_node: 250
 # max_per_epoch_activation_churn_limit: 8 <-- setting this explicitly does not solve the issue
launch_additional_services: true
additional_services:
  - assertoor
  - dora
snooper_enabled: true
disable_peer_scoring: true
assertoor_params:
 # ... bunch of assertions
```
